behaviors:
  Rover:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 20000
    threaded: true

environment_parameters:
  target_x:
    curriculum:
      - name: WaterPoint # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 33.66
          #target_y: 6.29
          #target_z: -76.13
  target_y:
    curriculum:
      - name: WaterPoint # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 6.29
  target_z:
    curriculum:
      - name: WaterPoint # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: -76.13
  waterEnabled:
    curriculum:
      - name: WaterPoint # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 0
  fastRestart:
    curriculum:
      - name: WaterPoint # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 0
  distancePlanesN:
    curriculum:
      - name: WaterPoint # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 6
  safeTraining:
    curriculum:
      - name: WaterPoint # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Rover
          signal_smoothing: true
          min_lesson_length: 100
        value: 1